### ISSUE TITLE
`ip.address` returns a different address from `ipconfig` in Windows

### ISSUE THREAD

**Issue by carpben** [indutny/node-ip#103]
When I run 
```js
var ip = require ("ip")
const deviceIp = ip.address()
console.log(deviceIp)
```
It prints a different address the IPv4 address that show on the `ipconfig` command. I must say that both addresses allow me to view the local server in the browser. What is the difference between those addresses? Why return a different value from the one IPconfig shows?

**Comment by olimexsmart** [comment]
By any chance do you have two network interfaces? 

i.e. connected both with WiFi and Ethernet

**Comment by carpben** [comment]
@olimexsmart , That was the case when I opened this issue, and once I understood that that was the source of the problem I managed to solve it. Closing this issue now. Thx
