### ISSUE TITLE
Audit vulnerabilities detected in the ip project on Tag: v1.1.5

### ISSUE THREAD

**Issue by mahirkabir** [indutny/node-ip#112]
**Issue**: We detected vulnerable dependencies in your project by using the command “npm audit”:
#### npm audit report

diff  <3.5.0
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/1631
fix available via `npm audit fix --force`
Will install mocha@9.0.3, which is a breaking change
node_modules/diff
  mocha  0.6.0 - 5.0.2
  Depends on vulnerable versions of diff
  Depends on vulnerable versions of growl
  node_modules/mocha

growl  <1.10.2
Severity: critical
Command Injection - https://npmjs.com/advisories/146
fix available via `npm audit fix --force`
Will install mocha@9.0.3, which is a breaking change
node_modules/growl
  mocha  0.6.0 - 5.0.2
  Depends on vulnerable versions of diff
  Depends on vulnerable versions of growl
  node_modules/mocha

js-yaml  <=3.13.0
Severity: high
Denial of Service - https://npmjs.com/advisories/788
Code Injection - https://npmjs.com/advisories/813
fix available via `npm audit fix`
node_modules/js-yaml

lodash  <=4.17.20
Severity: high
Prototype Pollution - https://npmjs.com/advisories/1065
Prototype Pollution - https://npmjs.com/advisories/1523
Command Injection - https://npmjs.com/advisories/1673
Prototype Pollution - https://npmjs.com/advisories/577
Prototype Pollution - https://npmjs.com/advisories/782
fix available via `npm audit fix`
node_modules/lodash
  babel-core  <=6.9.1
  Depends on vulnerable versions of babel-plugin-proto-to-assign
  Depends on vulnerable versions of lodash
  Depends on vulnerable versions of minimatch
  node_modules/babel-core
    babel-jscs  <=2.0.5
    Depends on vulnerable versions of babel-core
    node_modules/babel-jscs
      jscs  >=1.11.2
      Depends on vulnerable versions of babel-jscs
      Depends on vulnerable versions of jscs-jsdoc
      Depends on vulnerable versions of lodash
      Depends on vulnerable versions of xmlbuilder
      node_modules/jscs
  babel-plugin-proto-to-assign  *
  Depends on vulnerable versions of lodash
  node_modules/babel-plugin-proto-to-assign
  jsdoctypeparser  1.2.0 - 2.0.0-alpha-5
  Depends on vulnerable versions of lodash
  node_modules/jsdoctypeparser
    jscs-jsdoc  >=1.1.0
    Depends on vulnerable versions of jsdoctypeparser
    node_modules/jscs-jsdoc
  xmlbuilder  2.5.0 - 4.2.0
  Depends on vulnerable versions of lodash
  node_modules/xmlbuilder

minimatch  <=3.0.1
Severity: high
Regular Expression Denial of Service - https://npmjs.com/advisories/118
fix available via `npm audit fix`
node_modules/babel-core/node_modules/minimatch
  babel-core  <=6.9.1
  Depends on vulnerable versions of babel-plugin-proto-to-assign
  Depends on vulnerable versions of lodash
  Depends on vulnerable versions of minimatch
  node_modules/babel-core
    babel-jscs  <=2.0.5
    Depends on vulnerable versions of babel-core
    node_modules/babel-jscs
      jscs  >=1.11.2
      Depends on vulnerable versions of babel-jscs
      Depends on vulnerable versions of jscs-jsdoc
      Depends on vulnerable versions of lodash
      Depends on vulnerable versions of xmlbuilder
      node_modules/jscs

underscore  1.3.2 - 1.12.0
Severity: high
Arbitrary Code Execution - https://npmjs.com/advisories/1674
fix available via `npm audit fix`
node_modules/underscore
  nomnom  >=1.6.0
  Depends on vulnerable versions of underscore
  node_modules/nomnom

15 vulnerabilities (13 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

**Questions**: We are conducting a research study on vulnerable dependencies in open-source JS projects. We are curious:
1. Will you fix the vulnerabilities mentioned above? (Yes/No), and why?:
2. Do you have any additional comments? (If so, please write it down):

For any publication or research report based on this study, we will share all responses from developers in an anonymous way. Both your projects and personal information will be kept confidential.

**Description**: Many popular NPM packages have been found vulnerable and may carry significant risks [1]. Developers are recommended to monitor and avoid the vulnerable versions of the library. The vulnerabilities have been identified and reported by other developers, and their descriptions are available in the npm registry [2].

**Steps to reproduce**:
- Go to the root folder of the project where the package.json file located
- Execute “npm audit”
- Look at the list of vulnerabilities reported

**Suggested Solution**: Npm has introduced the “npm audit fix” command to fix the vulnerabilities. Execute the command to apply remediation to the dependency tree.

**References**:
2019. 10 npm Security Best Practices.  https://snyk.io/blog/ten-npm-security-best-practices/.
2021. npm-audit. https://docs.npmjs.com/cli/v7/commands/npm-audit.

**Comment by indutny** [comment]
I've updated everything to the latest, but even these outdated dependencies were only used for running tests. The module doesn't have any real dependencies!

**Comment by mahirkabir** [comment]
Hi! Thanks for the response.
