### ISSUE TITLE
[BUG] error: var numberOfAddresses = 2 ** (32 - maskLength); SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by into-piece** [indutny/node-ip#116]
// lib/ip.js
var numberOfAddresses = 2 ** (32 - maskLength)
SyntaxError: Unexpected token *

node version: v6.16.0

**Comment by indutny** [comment]
Oops. Missed that! Should be fixed by 8e6f28b. Thanks!

**Comment by into-piece** [comment]
> Oops. Missed that! Should be fixed by [8e6f28b](https://github.com/indutny/node-ip/commit/8e6f28b23a89245eeac74ad2ef9eb0d27cb27e1c). Thanks!

Plz update as soon as possible

**Comment by indutny** [comment]
@indutny I released 1.1.8 a day ago. Could you give it a try?
