### ISSUE TITLE
Swapped private and public IP?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [indutny/node-ip#57]
Hi,

I'm using your latest version of the package and I found a weirdo issue. Whenever I try to call the `.address()` API, I get swapped values. See the following snippet:

```js
ip.address( 'private', 'ipv4' ) // 192.168.1.254
ip.address( 'public', 'ipv4' ) // 127.0.0.1
```

Why? Any help is really appreciated.

Thanks in advance!

**Comment by bryanwayb** [comment]
Hey @julianxhokaxhiu, good catch. Trouble was backwards logic on an array filter in [lib/ip.js, line 388](https://github.com/indutny/node-ip/blob/e5b399ba10fbaf83d5d4904af624544322939439/lib/ip.js#L388). That code has been like that for at least 3 years, surprised it wasn't caught sooner...

The latests commits have the fix.

**Comment by julianxhokaxhiu** [comment]
Can you push / Did you push this to NPM?

**Comment by bryanwayb** [comment]
No, I haven't done a publish.

Hey @indutny, could you do a publish please? I've already incremented the version number.

**Comment by indutny** [comment]
Done, sorry for delay!

**Comment by julianxhokaxhiu** [comment]
Thank you!
