### ISSUE TITLE
fromPrefixLen returns wrong result with PhantomJS

### ISSUE THREAD

**Issue by dydek** [indutny/node-ip#60]
Hi, 
I was trying to use `ip.fromPrefixLen(20)` function, but it gives me `-1.-1.-1.-256` as a result. 
It is happening only with PhantomJS testing, when I use it with a "normal" browser, it works perfectly.

**Comment by indutny** [comment]
Sorry, it's been ages since you opened this. Finally fixed!

**Comment by dydek** [comment]
great, thx !
